<a href="https://colab.research.google.com/github/ghafooretemad/pytorch-learning/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

Tensor is like numpy ndarray that run in all kinds of hardware like GPU
Tensor can be initialised in different ways like:

In [2]:
input_data = [[2,4,5], [1,3,5], [3,6,7]]
my_tensor = torch.tensor(input_data)
print(my_tensor)

tensor([[2, 4, 5],
        [1, 3, 5],
        [3, 6, 7]])


Tensor can be created from numpy array

In [3]:
np_array = np.array(input_data)
np_tensor = torch.from_numpy(np_array)
print(np_tensor)

tensor([[2, 4, 5],
        [1, 3, 5],
        [3, 6, 7]])


Tensor can be created from another tensor

In [4]:
my_tensor1 = torch.ones_like(my_tensor)
print(my_tensor1)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


We can modify data type of tensor

In [5]:
my_tensor2 = torch.rand_like(my_tensor1, dtype=torch.float)
print(my_tensor2)

tensor([[0.8906, 0.5922, 0.6427],
        [0.0410, 0.4123, 0.6664],
        [0.3942, 0.9168, 0.1150]])


In the following example, shape is a tuple of tensor dimension

In [6]:
shape = (3,4)
my_dm_tensor = torch.rand(shape)
print(my_dm_tensor)

tensor([[0.5216, 0.9368, 0.2742, 0.0316],
        [0.0261, 0.1295, 0.5943, 0.2149],
        [0.6541, 0.0401, 0.1457, 0.6763]])


**Attributes of a Tensor**
attributes of a tensor are as follow:


1.   Data Type fo the Tensor
2.   Shape of the Tensor
3.   Device that Tensor Stored



In [7]:
shape = (5,8)
tensor = torch.rand(shape)
print(f"Shape of the Tensor: {tensor.shape} ")
print(f"Data Type of the Tensor: {tensor.dtype}")
print(f"Stored Device of the Tensor: {tensor.device}")

Shape of the Tensor: torch.Size([5, 8]) 
Data Type of the Tensor: torch.float32
Stored Device of the Tensor: cpu


**Tensor Operations**
There are 100 of tensor operations in pytorch documentation. 
like including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described [Here](https://pytorch.org/docs/stable/torch.html)

**Running Device**
Tensor can be run in CPU or GPU. 
we can check the availability of the GPU then we can set the enviroment using .to method

In [8]:
if(torch.cuda.is_available()):
  tensor = tensor.to("gpu")
  

**lets try some operations on Tensor**

In [10]:
myTensor = torch.ones(3,4)
print(f"First row: {myTensor[0]}")
print(f"First column: {myTensor[:, 0]}")
print(f"Last column: {myTensor[..., -1]}")
myTensor[:,1] = 0
print(myTensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1.])
Last column: tensor([1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
