<a href="https://colab.research.google.com/github/ghafooretemad/pytorch-learning/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

Tensor is like numpy ndarray that run in all kinds of hardware like GPU
Tensor can be initialised in different ways like:

In [5]:
input_data = [[2,4,5], [1,3,5], [3,6,7]]
my_tensor = torch.tensor(input_data)
print(my_tensor)

tensor([[2, 4, 5],
        [1, 3, 5],
        [3, 6, 7]])


Tensor can be created from numpy array

In [4]:
np_array = np.array(input_data)
np_tensor = torch.from_numpy(np_array)
print(np_tensor)

tensor([[2, 4, 5],
        [1, 3, 5],
        [3, 6, 7]])


Tensor can be created from another tensor

In [6]:
my_tensor1 = torch.ones_like(my_tensor)
print(my_tensor1)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


We can modify data type of tensor

In [7]:
my_tensor2 = torch.rand_like(my_tensor1, dtype=torch.float)
print(my_tensor2)

tensor([[0.8051, 0.4832, 0.9517],
        [0.6698, 0.5599, 0.4168],
        [0.4600, 0.9092, 0.8396]])


In the following example, shape is a tuple of tensor dimension

In [8]:
shape = (3,4)
my_dm_tensor = torch.rand(shape)
print(my_dm_tensor)

tensor([[0.0396, 0.6444, 0.2491, 0.4742],
        [0.8447, 0.4653, 0.1775, 0.8452],
        [0.6074, 0.7293, 0.5779, 0.3942]])


**Attributes of a Tensor**
attributes of a tensor are as follow:


1.   Data Type fo the Tensor
2.   Shape of the Tensor
3.   Device that Tensor Stored



In [11]:
shape = (5,8)
tensor = torch.rand(shape)
print(f"Shape of the Tensor: {tensor.shape} ")
print(f"Data Type of the Tensor: {tensor.dtype}")
print(f"Stored Device of the Tensor: {tensor.device}")

Shape of the Tensor: torch.Size([5, 8]) 
Data Type of the Tensor: torch.float32
Stored Device of the Tensor: cpu
